### ISSUE TITLE
Casting doesn't work on a Nest Home Hub Max

### ISSUE THREAD

**Issue by bogosj** [MarcoLucidi01/ytcast#1]
It appears that this only works for devices which have the YouTube app installed on them. Do you know if there's an alternate method to cast a video to a surface that doesn't have the app?

```
pi@raspberrypi:~ $ ytcast -n attic https://www.youtube.com/watch?v=kt4Z2AA5Kj0
ytcast: "Attic display": GetAppInfo: "YouTube": GET http://192.168.86.42:8008/apps/YouTube: 404 Not Found: bad HTTP response status
```

**Comment by MarcoLucidi01** [comment]
> It appears that this only works for devices which have the YouTube app installed on them.

correct, `ytcast` relies on the DIAL protocol to discover devices and on the YouTube on TV app to actually play videos via the Lounge api.

from the error it seems that your device supports the DIAL protocol, but as you noted, it doesn't have the app. can it be installed by any chance? or maybe the app is not integrated with DIAL.

> Do you know if there's an alternate method to cast a video to a surface that doesn't have the app?

there is [mkchromecast](https://github.com/muammar/mkchromecast) which works with Google Cast devices.
[Miracast](https://en.wikipedia.org/wiki/Miracast) also comes to my mind, but that's more like "whole screen sharing". I don't know a tool for that.

**Comment by bogosj** [comment]
I think I looked at mkchromecast before but if I recall I couldn't get it working because it requires node.js which doesn't have an ARMv6 version.

As best I can tell the Nest Home Hub Max doesn't support apps of any kind, it's akin to the older versions of the Chromecast which are not Android based. I may poke around and see if I can figure out an alternate way to initiate a cast from Go building upon what you've done here. I'll let you know what I find out.

**Comment by MarcoLucidi01** [comment]
> I may poke around and see if I can figure out an alternate way to initiate a cast from Go building upon what you've done here. I'll let you know what I find out.

sounds great! happy hacking!
