### ISSUE TITLE
RFE: Associate playback to a specific YouTube account

### ISSUE THREAD

**Issue by hadess** [MarcoLucidi01/ytcast#10]
I usually use the YouTube mobile phone app, logged in to my YouTube account, connected to an Apple TV box running the YouTube app. Videos played on the Apple TV app are controllable through the app (most notably seeking), and videos are marked as played in my account.

I'd like to be able to do the same thing from my Linux laptop, with playback progress being recorded on my account.

**Comment by MarcoLucidi01** [comment]
hi @hadess, i think that login and pause/unpause/seek/next/prev controls are out of scope for `ytcast`: its main goal and core functionality is to just cast (i.e. send) videos to play to a smart tv, any other playback control is left to the tv remote or the youtube app.
during the implementation i intentionally avoided those features and this allows `ytcast` to depend on a smaller portion of the scraped API for its core functionality that is *less* likely to break.

i do understand that video playback history associated to your youtube account would be useful, but atm there is no support for login/authentication and i don't think it is feasible with the API that `ytcast` relies on.

as for pause/unpause/seeks controls, there is this project which i used during the development of `ytcast` that supports those features: https://github.com/mutantmonkey/youtube-remote, hope will be useful to you.
