### ISSUE TITLE
Persistent device configuration

### ISSUE THREAD

**Issue by Atemu** [MarcoLucidi01/ytcast#12]
`ytcast` works great but I find it a bit annoying that I have to pass the `-d` flag every time I invoke `ytcast`. I'd prefer to be able to just simply call ytcast from any context (i.e. from a launcher rather than a shell) and it just uses a device that I selected once by default.

It'd be great if you could persist the device identifier somehow such that just `ytcast <url>` uses it.  `-d` should then override the default device.

When pairing a device, it should automatically become the default and there should be CLI flags to change the default device.

Ideally persist this in the `XDG_CONFIG_HOME` using a standard configuration format such as TOML.

**Comment by MarcoLucidi01** [comment]
hello @Atemu, thank you for reaching out.

i think we can already achieve *more or less* what you want:

- there is the `-p` flag which automatically selects the *last used device* in the cache.

- you could create an alias in your shell with your preferred device, for example: `alias ytcast='ytcast -d lgtv'`, then `ytcast <url>` will automatically use the `lgtv` device. if you provide another `-d`, it will override the one written in the alias.

let me know if this works for you.

i don't think i'll going to introduce a config file. i think that the command line options are flexible enough.

**Comment by Atemu** [comment]
I didn't notice this flag; that solves this issue.

It'd be great if there was a man page that'd explain the flags using more than a half-sentence.
